# Generated by Django 5.1.2 on 2024-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
