# Generated by Django 5.1.2 on 2024-11-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_email_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='educacao',
            field=models.CharField(choices=[('Higher education (one or more)', 'Higher education (one or more)'), ('Secondary education (plus special education)', 'Secondary education (plus special education)'), ('Incomplete higher education', 'Incomplete higher education'), ('Primary or lower secondary education', 'Primary or lower secondary education')], default='Secondary education (plus special education)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('Married', 'Married'), ('Single/unmarried', 'Single/unmarried'), ('Divorced/widow', 'Divorced/widow')], default='Single/unmarried', max_length=20),
        ),
    ]
