# Generated by Django 5.1.1 on 2024-12-04 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_educacao_alter_cliente_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='marker',
        ),
    ]
